### PR TITLE
feat: Add S390x support 

### PR DESCRIPTION
**Pull request by modassarrana89**
#### Modifications
Added linux/s390x ( platform ) in the build github workflow 

#### Result
https://github.com/modassarrana89/modelmesh/actions/runs/8688245342/job/23823937204 // Build operation run in local workflow is a success. Attached archieve log for refernece
[logs_22763759557.zip](https://github.com/kserve/modelmesh/files/14978607/logs_22763759557.zip)

### CODE REVIEW

**Comment by modassarrana89** [comment]
@njhill @rafvasq Please review the change

**Review by spolti — APPROVED** [review]

**Comment by modassarrana89** [comment]
@spolti Please merge , as you have approved the change.

**Comment by spolti** [comment]
> @spolti Please merge , as you have approved the change.

It is up to @njhill and @rafvasq  :)

**Comment by modassarrana89** [comment]
@njhill & @rafvasq Please review & do the needful.

**Review by rafvasq — APPROVED** [review]
Thanks for the update @modassarrana89, looks like GRPC [added support for s390x](https://github.com/grpc/grpc-java/issues/8191) a while ago.

**Comment by modassarrana89** [comment]
> Thanks for the update @modassarrana89, looks like GRPC [added support for s390x](https://github.com/grpc/grpc-java/issues/8191) a while ago. Please rebase this with main again when you can.

I have done that. Can you please merge the PR now

**Review by rafvasq — APPROVED** [review]
/lgtm

**Pull request merged**
