### PR TITLE
Added reader rewind to remote payload processor

### PR DESCRIPTION
**Pull request by RobGeada**
#### Motivation
Addresses https://github.com/kserve/modelmesh/issues/111. 

#### Modifications
Adds a byteBuf readerIndex rewind before payloads are parsed in the RemotePayloadProcessor, which deals with any concurrency issues arising from a too-early read of a queued payload. This is a workaround that mitigates the effects of some unknown race condition in bytebuf reading, which should likely still be addressed, but this works in the interim. 

#### Result
Null response payloads no longer occur in high-process-time scenarios

### CODE REVIEW

**Review by ckadner — CHANGES_REQUESTED** [review]
Hi @RobGeada -- could this change be tested in a unit test?

**Comment by RobGeada** [comment]
@ckadner any updates?

**Review by ckadner — COMMENTED** [review]
Thanks for adding the unit tests. 

Going back to your investigation:
> It looks like the response `bytebufs` are read too early somewhere, causing their `readerIndex` to equal their capacity at processing time. This read occurs somewhere between their addition to the queue in the `AsyncPayloadProcessor` but before `payloads.take()` is called. A **hacky** patch is to call `byteBuf = byteBuf.readerIndex(0);` as the first line in `RemotePayloadProcessor.encodeBinaryToString()`, to reset their reader index, and indeed this prevents the issue from arising

Could you add a comment above the line that resets the `readerIndex` to explain why it is necessary.

Should we spend the time to find out where the response `bytebufs` are read too early and why. If that read happens erroneously, it might cause problems in other places as well?

**Comment by njhill** [comment]
Thanks @RobGeada. I've opened another PR  which will hopefully address this properly, would you mind reviewing that?

It would also be useful to have a unit test for this, but the tests included here don't exercise the actual bug. Ideally we'd have a test that actually runs a local modelmesh with an asyncprocessor configured and can trigger the problem (other unit tests already run modelmesh to test other stuff and could hopefully be used as a starting point and adapted).

**Comment by ckadner** [comment]
Should this PR be closed in favor of PR #120 ?

**Comment by njhill** [comment]
> Should this PR be closed in favor of PR https://github.com/kserve/modelmesh/pull/120 ?

@ckadner yes!  @RobGeada would be great if you could review #120

**Pull request closed without merging**
